sudo: false
language: node_js
node_js:
  - "8"
  - "9"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false 

before_script:
  - npm prune
script:
  - npm run e2e
  - npm run lint
   - npm run test
after_success:
  - npm run build
  