sudo: false
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: true

before_script:
  - npm prune
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
  - npm run e2e
  - npm run lint
   - npm run test
after_success:
  - npm run build
  