sudo: false
dist: xenial
addons:
  chrome: stable
language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: true

before_script:
  - npm prune
  
script:
  - xvfb-run npm run e2e
   - npm run lint
   - npm run test
after_success:
  - npm run build
  