# sudo: required
# dist: trusty
# addons:
#   chrome: stable
# language: node_js
# node_js:
#   - "9"
# cache:
#   directories:
#     - node_modules
# branches:
#   only:
#     - master
# notifications:
#   email: true

# before_script:
#   - npm prune
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start

  
# script:
#   - xvfb-run npm run e2e
#    - npm run lint
#    - npm run test
# after_success:
#   - npm run build
  
sudo: required
dist: trusty

addons:
  chrome: stable
  
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
    - /^greenkeeper/.*$/

notifications:
  email: false 

 before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm uninstall webpack
  - npm remove webpack
  - npm install webpack@3.11.0 --save
  - npm run ci
  
