
sudo: false
language: node_js
node_js:
  - "8"



cache:
  directories:
    - node_modules

  before_script:
  - npm prune
  
script:
# - npm uninstall webapack --save
# - npm remove webpack
# - npm install webpack@3.11.0 --save
- npm run lint
- npm run build 

    